name: opf
services:
  db:
    image: postgres:18.4-alpine3.22
    restart: always
    shm_size: 128mb
    environment:
      TZ: ${API_TIME_ZONE}
      POSTGRES_DB: ${API_DB_NAME}
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASS}
      POSTGRES_INITDB_ARGS: '--auth=md5'
    healthcheck:
      test: pg_isready -U "${DB_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql
    command: >
      postgres
      -c shared_buffers=2GB
      -c effective_cache_size=4GB
      -c work_mem=8MB
      -c maintenance_work_mem=256MB
      -c max_connections=60
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '3'
    ports:
      - '5432:5432'
    networks:
      - opf-net

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      TZ: ${API_TIME_ZONE}
    restart: always
    volumes:
      - ./.venv:/code/.venv
      - ./logs:/code/logs
      - ./media:/code/media
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '3'
    #    tty: true
    #    stdin_open: true
    #    command: [ "bash", "-l" ]
    command: >
      bash -lc "cd /code;
                bash manage.sh update;
                bash manage.sh compile;
                exec bash manage.sh start --prod --back"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '8000'
    ports:
      - '8000:8000'
    networks:
      - opf-net

volumes:
  db_data:

networks:
  opf-net:
    external: false
