name: Scheduled Merge

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  code-check:
    uses: ./.github/workflows/check.yaml
    with:
      ref: ''

  merge:
    needs:
      - code-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Check for diff
        id: check_diff
        run: |
          git fetch origin develop
          git diff --quiet origin/main || echo "HAS_DIFF=true" >> $GITHUB_ENV

      - name: Merge to main
        if: env.HAS_DIFF == 'true'
        run: |
          git config user.name "Bot"
          git config user.email "bot@one-coder.com"

          git fetch origin main:main
          git checkout main
          git merge --no-ff --allow-unrelated-histories origin/develop -m "Automated daily merge from develop to main"
          git push origin main
